### ISSUE TITLE
NullPointerException in TabEntry

### ISSUE THREAD

**Issue by PrestigePvP** [alexandeh/Kraken#2]
In the method "send" in TabEntry, there is an NPE on team.setPrefix(text), and team.setSuffix(""); 
Team isn't nulll (I made a check for that), so either its with the API or something I'm doing.

**Comment by PrestigePvP** [comment]
Didn't figure it out, but I made my own. Its okay, thanks for the base of the idea, and basis of using teams.

**Comment by bizarre** [comment]
Yeah, I'd release a public API that's completely unusable and throws a null pointer when you try to implement it. Cringe
